### ISSUE TITLE
Wrong archive format detection patterns

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#112]
# Bugs

Here's a bug: 

https://github.com/ouch-org/ouch/blob/2e6cd893dcde49fbb0cf7bb8719abf0069003edb/src/commands.rs#L58

Here's another:

https://github.com/ouch-org/ouch/blob/2e6cd893dcde49fbb0cf7bb8719abf0069003edb/src/commands.rs#L195

# Reason

In both cases we are pattern matching to see if the file is an archive or not.

Formats that are archives: `tgz`, `tar`, `zip`, `tzst`, `zstd`, etc.
No archives: `xz`, `gz`, `bz`, `zst`.

However, we added new variants and forgot to update these patterns to match.

https://github.com/ouch-org/ouch/blob/2e6cd893dcde49fbb0cf7bb8719abf0069003edb/src/extension.rs#L8-L20

# Solution

Add method to `CompressionFormat` called `is_archive_format` and use it and it's negation instead.

Then check for each non-exhaustive pattern matching done in `ouch` with `if let`, `matches!` and `match`. Reviewing if should be replaced by a call of `format.is_archive_format()` (or `!format.is_archive_format()`)

**Comment by marcospb19** [comment]
Setting the priority to `urgent` because we can't make any releases with such bug.

**Comment by SpyrosRoum** [comment]
Also here I'm not sure if we actually need to much the rest of the archive formats, and if we do then what do we have to do with them in the match?
https://github.com/ouch-org/ouch/blob/2e6cd893dcde49fbb0cf7bb8719abf0069003edb/src/commands.rs#L195-L212

**Comment by SpyrosRoum** [comment]
I believe keeping only the `else` part is fine but I am having some issues with tests

> Formats that are archives: tgz, tar, zip, tzst, zstd, etc.
> No archives: xz, gz, bz, zst.

Ahm is `zstd` the same as `zst`? Because `CompressionFormat::Zstd` formats to `.zst`

**Comment by SpyrosRoum** [comment]
It's just that some tests try to compress to `tar.zst` and I took `zst`/`zstd` as an archive format so according to the changes it doesn't allow it
