### ISSUE TITLE
Changing `--output` to `--dir`

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#115]
# Suggestion

Replace the `-o/--output` flag of the `decompress` subcommand by `-d/--dir`.

# Why?

```
OPTIONS:
    -o, --output <OUTPUT>    Decompress files in a directory other than the current
```

`--output` usually is referred to the file that is created, but in this case it's about the output directory.

Example: `gcc main.c --output main`.

Example: `ouch compress 1 2 3 archive.tar.gz`, 
If you check the _help_ for the subcommand `compress`, we the argument `archive.tar.gz` is the `<OUTPUT>` positional arg, again, has no relation to directories or folders, but output file instead.

**Comment by Onyinye91-ctrl** [comment]
@marcospb19 I want to work on this. Can you assign to me? Also i want to know the directory to find the file
