### ISSUE TITLE
Decompression error when folder already exists at the place of output file

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#136]
![image](https://user-images.githubusercontent.com/38900226/139797532-3def4fb6-b631-4402-b672-7042a921feb8.png)

Ouch doens't really know that there is a folder there, it just gives this error message.

When it's not a folder, but a simple text file, it does ask if should overwrite.

**Comment by SpyrosRoum** [comment]
Should we ask to overwrite if there is a directory as well or simply improve the error message?

**Comment by marcospb19** [comment]
I think we should ask like we do for other regular files.

**Comment by SpyrosRoum** [comment]
> When it's not a folder, but a simple text file, it does ask if should overwrite.

Unless I'm doing something wrong, this is not true, it simply overwrite the file:
![image](https://user-images.githubusercontent.com/38166823/139808085-cda9c2a5-1bb1-4bf6-b063-025b77b61349.png)

**Comment by marcospb19** [comment]
Try it with an archive format, seems like overwrite questions are not being asked for single-file compression formats? (like .gz .xz .bz .zst).

**Comment by SpyrosRoum** [comment]
I think the issue in essentially the same and I'm in the process of fixing it all so is it okay if I do them in the same pr?

**Comment by marcospb19** [comment]
Sure!

**Comment by marcospb19** [comment]
Still an issue, probably at:
https://github.com/ouch-org/ouch/blob/7a4dcb2074d3814918eb4ec098fa16c61c15396e/src/utils/fs.rs#L23-L30


How to reproduce:

![image](https://user-images.githubusercontent.com/38900226/141110914-9bc84a01-d95c-461e-b426-1a558f5b1218.png)

**Comment by SpyrosRoum** [comment]
Hm I guess I missed that case but it seems like an easy fix
