### ISSUE TITLE
Try to infer file extension as fallback when decompressing

### ISSUE THREAD

**Issue by sigmaSd** [ouch-org/ouch#145]
Here is a code example: https://github.com/sigmaSd/ouch/commit/282324455bded82ac007e3fe66736e90de77a857

**Comment by marcospb19** [comment]
Related to #142

**Comment by sigmaSd** [comment]
The usecase Im thinking is a file without extention

Ouch can print something like: "Detected file type tar , do you want to decompres it?"

But I dont know how common this use case is (maybe not at all)

Feel free to close this issue if you think this should not be supported

**Comment by marcospb19** [comment]
It's really similar to what I proposed in #142, I think it can be a great addition, but I'd ask you to first implement it as a warning using the `info!` macro.

This warning would be emitted even if the file has extensions, but the implementation would be very similar.

About if the [Y/n] question should or not be asked in the **specific case** when no extensions are given, I'd like to wait on @vrmiguel and others opinion.

**Comment by sigmaSd** [comment]
Also another idea is when Ouch is done decompressing, it should detect the detect if the decompressed file is also an archive and prompt the user to decompress it if so.

**Comment by marcospb19** [comment]
You need to add "fixes #145" in the PR to link them and automatically close issues on merge.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by sigmaSd** [comment]
I see thanks I'll keep that in mind.
