### ISSUE TITLE
Automatically decompress the archive into a directory if there is no directory for the contents in the archive

### ISSUE THREAD

**Issue by c02y** [ouch-org/ouch#151]
For instance, I got a zip file containing multiple dirs and files in it, but they have no parent directory.

When you decompress it using `ouch d dir.zip` all the contents will be decompressed into the current directory which may already contains a lot of other dirs or files.

It is better to automatically decompress the archive into a new directory, the name of the directory should be the file name of the archive without the extension. If you think it is not a good idea by default, an option can be provided.

For example, command `unar` can do it(`unar` is the command from `unarchiver` package, link is https://github.com/MacPaw/XADMaster)

**Comment by GabrielSimonetto** [comment]
Yea, this probably should be the default config, and if someone wants to unpack inplace we can provide a flag for that

**Comment by marcospb19** [comment]
This practically discards the necessity of the `ouch revert` command I thought about to clean up, reverting everything that was done in the last command.

**Comment by sigmaSd** [comment]
I think ouch already does this for single file formats, so maybe a simple patch like this is enough to add this behavior for archive file formats:
 
```diff
diff --git a/src/commands.rs b/src/commands.rs
index 7550bae..8051de0 100644
--- a/src/commands.rs
+++ b/src/commands.rs
@@ -338,7 +338,8 @@ fn decompress_file(
         if let Some(output_dir) = output_dir { output_dir.join(file_name) } else { file_name.to_path_buf() };
 
     // Output folder is used by archive file formats (zip and tar)
-    let output_dir = output_dir.unwrap_or_else(|| Path::new("."));
+    let owned_file_name = file_name.to_path_buf();
+    let output_dir = output_dir.unwrap_or_else(|| &owned_file_name);
 
     // Zip archives are special, because they require io::Seek, so it requires it's logic separated
     // from decoder chaining.
```

**Comment by runiq** [comment]
> I think ouch already does this for single file formats, so maybe a simple patch like this is enough to add this behavior for archive file formats:
> 
> ```diff
> diff --git a/src/commands.rs b/src/commands.rs
> index 7550bae..8051de0 100644
> --- a/src/commands.rs
> +++ b/src/commands.rs
> @@ -338,7 +338,8 @@ fn decompress_file(
>          if let Some(output_dir) = output_dir { output_dir.join(file_name) } else { file_name.to_path_buf() };
>  
>      // Output folder is used by archive file formats (zip and tar)
> -    let output_dir = output_dir.unwrap_or_else(|| Path::new("."));
> +    let owned_file_name = file_name.to_path_buf();
> +    let output_dir = output_dir.unwrap_or_else(|| &owned_file_name);
>  
>      // Zip archives are special, because they require io::Seek, so it requires it's logic separated
>      // from decoder chaining.
> ```

This creates the directory unconditionally. I'll try and have a go at this. I've barely written a Rust so far, though, so if anyone's faster than me I'm happy to defer. :)

**Comment by marcospb19** [comment]
@runiq take your shot at this one.

You might want to create a draft PR asking for help on some part, if necessary.

**Comment by runiq** [comment]
So after looking over the code, it appears the only reasonable way to go about this would be to unpack each archive into a temporary directory and rename it (if the archive file contains multiple files in the root) or move out of it (if it contains only a single file).

I was hopeful I could get the list of files from an archive without having to iterate over it, but that's not possible with tar.

**Comment by marcospb19** [comment]
I'm not a huge fan of writing stuff down and moving it afterwards, **but** if it's only for one file, I guess it's ok.

@runiq for `zip` we know the number of files in an archive before decompressing, so no need to move anything, just for `tar`.

**Comment by runiq** [comment]
Sorry, stomach bug had me tied to the bed. :( I'll try and look into it today

**Comment by marcospb19** [comment]
No worries, you may take the rest of the year to do this if you wish to.

**Comment by sigmaSd** [comment]
I tried this but it turns out it has a lot of different little edge cases.

I think that creating the directory unconditionally like the patch I posted above is actually a reasonable solution.

**Comment by sigmaSd** [comment]
But I guess at that point it the same as --dir

So this issue is really about that automatic behaviour that handle all cases magicly, which makes sense and its definitly possible

**Comment by marcospb19** [comment]
Soooo @sigmaSd, I don't think you did it by purpose, and all contribution PRs are welcome, but I think that @runiq said he/she was going to take a look at this, and got sick or something.

I'd just ask to be careful cause it can be frustating to put effort on a contribution and it becoming useless later (if @runiq already had some work in progress, that would be instantly discarted).

I could also have made it more clear that it was assigned to someone, so I'll try to remember to do so in future conversations.

**Comment by sigmaSd** [comment]
I see your point, I just got interested in the technicality more then anything, eitherway its just a draft pr so I went ahead and close it
runiq should feel free to take anything from that pr if there is something interesting there

**Comment by runiq** [comment]
No no, it's totally okay, as I mentioned! Have at it @sigmaSd :) I'm afraid Covid-19 is now making the rounds in my gf's daughter's class, so I've still got my hands a little full ATM :(

**Comment by sigmaSd** [comment]
Ok, hopefully they remain safe

**Comment by figsoda** [comment]
I'm worried that this will make `ouch c * foo.tar && ouch d foo.tar` have inconsistent results depending out how many file was globbed

**Comment by sigmaSd** [comment]
It will definitely be inconsistent depending if decompressing needs to create a folder or not, but can you elaborate on why would that (the inconstancy) be a problem?

**Comment by figsoda** [comment]
It might break scripts that use `*` to glob files and is non-trivial to fix

**Comment by marcospb19** [comment]
@runiq I hope everything will be fine with them!

---

About this issue still, @figsoda the other option would be to have a `reverse` command that reverts everything that was done in the last time `ouch` was ran.

If it created 100 files, would delete all of them.

Let's say you ran this command:

```rust
ouch decompress a.tar.gz
```

To revert it, just add the `revert` command:
```rust
ouch revert decompress a.tar.gz
```

So the person can run it again with `--dir`.

If we want log to some file instead:
```rust
ouch revert
```

But maybe logging is too much.

---

Just wanted to show this alternative to get some feedback, both solve the problem of having stuff thrown around when decompressing.
