### ISSUE TITLE
Incorrect Extension Handling

### ISSUE THREAD

**Issue by dtomvan** [ouch-org/ouch#165]
Bug Report:

### Test case 1: 
`ouch c /home/tomvd/.bashrc /home/tomvd/.bashrc.tar.bz2 && file /home/tomvd/.bashrc.tar.bz2`
```Compressing '.bashrc'.
[INFO] Successfully compressed '/home/tomvd/.bashrc.tar.bz2'.
/home/tomvd/.bashrc.tar.bz2: gzip compressed data, original size modulo 2^32 2048
```

- Observed behaviour: `ouch` compresses to a gzip
- Expected behaviour: `ouch` compresses the file to a bzipped tarball  e.g:
```
~> tar cf .bashrc.tar .bashrc
~> bzip2 .bashrc.tar
~> file .bashrc.tar.bz2
.bashrc.tar.bz2: bzip2 compressed data, block size = 900k
```

### Test case 2: 
`ouch c /home/tomvd/.bashrc /home/tomvd/.bashrc.gz`
```
thread 'main' panicked at 'internal error: entered unreachable code', /home/tomvd/.cargo/registry/src/github.com-1ecc6299db9ec823/ouch-0.2.0/src/commands.rs:162:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

- Observed behaviour: `ouch` panics and creates an empty `.bashrc.gz`
- Expected behaviour: `ouch` compresses to a bzip

**Comment by dtomvan** [comment]
Oops, the second test case is #31 and will be fixed with #163.

**Comment by figsoda** [comment]
actually second test case was already fixed in #89
#163 is just improving tests so we can find problems like this

**Comment by figsoda** [comment]
first case seems to be fixed on master too

**Comment by dtomvan** [comment]
Oh I'm sorry, I just reported this because the version I'm on (I think from crates.io) had these bugs.

**Comment by figsoda** [comment]
Did you update to 0.3.1? It was delayed a little bit, but both of these should be fixed in 0.3.1

**Comment by marcospb19** [comment]
I think I should create an issue template to remember people to send the `ouch` version they are using (nobody remembers this xD).

**Comment by marcospb19** [comment]
Done, now ouch has two new templates, they don't do much, but at least has a reminder for this.
