### ISSUE TITLE
[FR] Autodect creating an output folder upon decompression

### ISSUE THREAD

**Issue by murlakatamenka** [ouch-org/ouch#169]
Since ouch is focused on ease of use and ergonomics I suggest to consider implementing the following flag for decompression.

[KDE's Ark](https://apps.kde.org/ark/) has `-a, --autosubfolder` flag:

> Archive contents will be read, and if detected  not be a single folder or a single file  a subfolder with the name of the will be created.

I use it all the time :smile: and find it really helpful for unarchiving stuff blindly, without preview.

**Comment by SpyrosRoum** [comment]
This is a duplicate of #151 but I agree it's a nice QoL to have

**Comment by murlakatamenka** [comment]
Yeah, right, that's essentially a duplicate.

**Comment by marcospb19** [comment]
Will be taking a look at it tho.
