### ISSUE TITLE
Add flag to skip files ignored by `.gitignore`

### ISSUE THREAD

**Issue by hoodie** [ouch-org/ouch#170]
Hi there!
Very nice tool. I'm wondering, since this is using walkdir I'd assume adding the [ignore](https://crates.io/crates/ignore) crate ought to be fairly straight forward. So `ouch` could have a feature where it automatically ignores certain files/folders like `./.git` or `./node_modules`or `./target` while compressing.

Would anybody be interested in this functionality?

thank you

**Comment by vrmiguel** [comment]
I like that idea :D

We could follow in `ripgrep`'s steps and respect gitignore rules and skip hidden files/directories

**Comment by hoodie** [comment]
yes, exactly. and the cool thing is that you get most of this for free by using `ignore` afaik

**Comment by marcospb19** [comment]
Fixed at https://github.com/ouch-org/ouch/pull/245 by @vrmiguel :rocket:.
