### ISSUE TITLE
Inconsistent `zip` compression and decompression memory usage warnings

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#178]
![image](https://user-images.githubusercontent.com/38900226/141111104-556d0b6e-f142-4827-85b9-d8b84e46d962.png)

The limitation of compressing zip archives with other streams only occurs when using multiple formats, like:

`archive.zip.gz`, or `archive.zip.xz.xz.xz.xz`.

`.zip` requires `io::Seek`, and it can only be provided in `fs::File` and `Vec<u8>`, so we can either compress directly to the final file, or load into a `Vec`, but not pipe to encoding streams.

Loading the whole file to a `Vec` might exhaust memory capacity, that's why we need to give those warnings in specific cases.

---

While filing this, I found out the `decompression` command has another warning with different formatting:

![image](https://user-images.githubusercontent.com/38900226/141111812-5d5b43ae-dec2-4335-971f-fb4f2d849e41.png)

These messages formats should be consistent.

**Comment by marcospb19** [comment]
Warning parts is related to #177.

**Comment by sigmaSd** [comment]
Apperently its possible to decompress zip as stream https://github.com/uktrade/stream-unzip

This should be easy to port to rust, but I have no idea how correct is this implementation

**Comment by marcospb19** [comment]
I'm still a bit skeptical, I think this is an unsolvable problem.

`zip` has this "metadata" part at the start of the archive that needs to be updated for each file that's added to it, so we cannot send the start of the archive while we don't finish it.

Meaning you add to a stream like `tar`, unless you have the "metadata" part ready at the start.

But we cannot solve the metadata upfront, because we'd need to load everything to memory and preprocess it, that wouldn't be better than decompressing/compressin everything to a `Vec`.

**Comment by Crypto-Spartan** [comment]
Created a PR to address the main issue. This is not a fix to stream compress/decompress `zip` archives.
