### ISSUE TITLE
Unspecified behavior when compressing overwritten file

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#180]
You build the archive:
```
ouch compress * archive.tar.gz
```

If you go there and run it again:
```
ouch compress * archive.tar.gz
```

It will ask "do you wish to overwrite `archive.tar.gz`?

If you press `Y`, it will delete the file, open a new file for `archive.tar.gz`, but note that the same file was also passed as an input for this compression! (with `*` wildcard)

The same file is the input and output.

`ouch` will read the output file to add as input to the... same output file.

Also:

```
ouch compress LICENSE a.zip
```
Then
```
ouch compress a.zip a.zip a.zip a.zip
```

---

Maybe just adding a `FinalError` for when the output file was passed as input too would solve it.

**Comment by SpyrosRoum** [comment]
Crashing feels a little too much. 
Maybe a warning and skipping that file is enough, thoughts?

**Comment by marcospb19** [comment]
I agree! That's a great idea actually, it's what `mv` does when you're trying to move the directory to inside of itself.

![image](https://user-images.githubusercontent.com/38900226/141316668-7f9517a1-eda3-4e48-a4ba-9c1a510ea972.png)
