### ISSUE TITLE
Don't use absolute paths

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#183]
We can remove the `fs::canonicalize` function calls, as they are only being currently used to check if files exist, this type of check should be performed with `fs::metadata` instead.

This is currently causing the problem that our error messages have the absolute paths, some workaround functions could even be removed, like `strip_cur_dir` simplifying our code.

Example of absolute path in error messages:

![image](https://user-images.githubusercontent.com/38900226/141209941-efb080e5-283c-45ed-92d4-1e86884dd97c.png)

**Comment by marcospb19** [comment]
I'll take a shot at fixing this.

**Comment by SpyrosRoum** [comment]
Hey marcospb19, are you still working on this?

**Comment by marcospb19** [comment]
Sadly not, I didn't even start it, I think this requires a medium refac just because it might break other parts of the code.

**Comment by marcospb19** [comment]
I don't think this does make sense anymore, canonicalized is only called for files passed as CLI args, not unpacked files.

There seems to be no clear benefit to this, it would require reviewing a lot of code to check for errors, and it possibly introduces some bugs because the whole codebase expects input file paths to be absolute.
