### ISSUE TITLE
Add supported formats info to `--help` message

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#185]
Probably only to the long `--help` message, and not the short `-h` one.

Currently supported formats are:

`| .tar | .zip | .bz, .bz2 | .gz | .lz4 | .xz, .lz, .lzma | .zst | `

**Comment by SpyrosRoum** [comment]
> Probably only to the long --help message, and not the short -h one.

FYI I don't think there is any difference between `--help` and `-h`, they are treated as aliases

**Comment by marcospb19** [comment]
Currently, no, but I think that's a bug with the version of clap we are using, probably related to https://github.com/clap-rs/clap/issues/2983, which is an issue explaining how clap switched from short to long help randomly.

In `fd` and `bat` the output of `-h` and `--help` do differ, maybe this isn't a thing in 3.0?
