### ISSUE TITLE
[DANGER] Decompressing with `.zip` can erase current directory contents

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#207]
### Version

ed68e17 (latest, thankfully not shipped in any stable release)

### Description

The line https://github.com/ouch-org/ouch/pull/190/files#diff-b86d43fce6a9c57160aa925719550d40a6ed3f5e5a0117679905f76e68acc520R345

Removes the current directory if the user doesn't use the --dir flag (because outputdir = ".")

and the message isn't obvious either:

```
Do you want to overwrite ''? [Y/n]
```

If you turn strip_cur_dir into this:

```rust
pub fn strip_cur_dir(source_path: &Path) -> &Path {
    source_path
}
```

The question prompt is now this one:
```
Do you want to overwrite '.'? [Y/n]
```

**Comment by sigmaSd** [comment]
I just want to add that this is fixed now in master

Whats left is improving the overwrite message

**Comment by marcospb19** [comment]
Ok, fixed by recent PR https://github.com/ouch-org/ouch/pull/206 from @sigmaSd.
