### ISSUE TITLE
hint suggestion for compressing multiple files has incorrect format

### ISSUE THREAD

**Issue by Crypto-Spartan** [ouch-org/ouch#218]
### Version

0.3.1

### Description

When executing the command `ouch compress 1 2 3 4 myarchive.zst` this is the output:

![image](https://user-images.githubusercontent.com/29098151/145119741-96690325-ef9c-4e84-b978-1b778d108428.png)

Notice that the last hint is incorrect in it's format.

### Expected Behavior

The output should look like this instead:

![image](https://user-images.githubusercontent.com/29098151/145119988-c4763c14-c782-4b02-b65f-c4be16a93896.png)

**Comment by marcospb19** [comment]
Oh well, I totally forgot to create this issue before, thanks.

**Comment by Crypto-Spartan** [comment]
No problem! Glad I could help
