### ISSUE TITLE
Incorrect warnings for decompression of tar extensions like tgz, txz, e.t.c

### ISSUE THREAD

**Issue by figsoda** [ouch-org/ouch#220]
### Version

master (bafc2d31b4dacf738ed6a82aa315df6ca2247fbb)

### Description

the special tar extensions are not recognized when decompressing and extra warnings are generated

### Current Behavior

```console
$ ouch c src src.tgz && ouch d src.tgz
[INFO] Compressing 'src'. [00:00:00]   4.00KiB/ (39.15KiB/s, 0s)
[INFO] Successfully compressed 'src.tgz'.
Warning: The file extension: `tgz` differ from the detected extension: `gz`
Do you want to continue decompressing '/home/figsoda/ouch/src.tgz'? [Y/n]
```

### Expected Behavior

no warnings

**Comment by marcospb19** [comment]
Format handling turned into a mess cause we added a lot of features and did bugfixes without proper refactoring and testing every case.

I'll be trying to improve that part of the code and fix this.
