### ISSUE TITLE
Remove `lib.rs` and move stuff to `main.rs`

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#234]
`ouch` currently has an `lib.rs` and `main.rs` file, which increases the compile time.

First it compiles the `lib.rs` crate part and then it compiles `main.rs`, plus, both operations cannot be parallelized.

By only having `main.rs` I think that the compilation time will improve a bit.

**Comment by Crypto-Spartan** [comment]
Is the goal of ouch to only be a command line tool, or is there a goal to also have a way for others to use ouch as a library?

I personally think that a lib.rs file is a benefit, but I understand if you only want to focus on the tool itself and not the library aspect.

**Comment by marcospb19** [comment]
I think we never planned on making the ouch library publicly available, maybe it wouldn't be that useful cause:

1. Ouch can panic suddenly.
2. We flood stdout and stdin with archive stuff.

It would require a lot of work to make it a decent library, maybe if one day someone gets interested in using ouch for another project, than this person can help the _libfication_ of ouch, it depends on the API needs.

The lib.rs is not currently being beneficial because we don't have a library crate published.
