### ISSUE TITLE
Add a peek feature

### ISSUE THREAD

**Issue by BLucky-gh** [ouch-org/ouch#235]
ouch already does a good job of being the one tool to compress/decompress various files, but there's still one thing that forces the user to look for the corresponding tool which is peeking/previewing the contents of the archive.

**Comment by marcospb19** [comment]
Can you confirm which version of `ouch` you're using? The upstream version (master branch) contains the command `ouch list` that does that for any .zip.* and .tar.* archive, maybe that's what you're looking for!

```
ouch list archive.tar.gz.bz.xz
```

**Comment by BLucky-gh** [comment]
Oh yeah turns out after a botched reinstall of the rust toolchain `cargo` stopped updating packages installed before the reinstall so turns out I had a pretty outdated version. thanks for pointing it out
