### ISSUE TITLE
Save metadata for extracted file(s)

### ISSUE THREAD

**Issue by ikrivosheev** [ouch-org/ouch#237]
Very often I download the archive of logs from the server. After unpacking, the timestamps of the files are not the same as on the server

**Comment by marcospb19** [comment]
Can you give an reproducible example?

It would be good to see an example where another tool does this correctly and `ouch` is doing it wrong.

If I understood correctly what you said, there is no way to keep the time stamps.

**Comment by ikrivosheev** [comment]
Yes. Simple example. 

1. I have two files:
```
>> ls -alh ~/projects/opensource/pa-notify/
-rw-r--r--  1 ikrivosheev ikrivosheev  180 Nov 10  2020 .gitignore
-rw-r--r--  1 ikrivosheev ikrivosheev 1.1K Nov 10  2020 LICENSE
```
2. Then create archive:
```
>> ouch c .gitignore LICENSE test.zip
```
3. Extract archive:
```
>> ouch d test.zip
[INFO] ".gitignore" extracted. (180.00 B)
[INFO] "LICENSE" extracted. (1.07 kB)
[INFO] Successfully decompressed archive in current directory.
>> ls -alh .
-rw-r--r--  1 ikrivosheev ikrivosheev  180 Jan 30 14:43 .gitignore
-rw-r--r--  1 ikrivosheev ikrivosheev 1.1K Jan 30 14:43 LICENSE
```
You can see `time of last modification` is change. 
4. Try to extract with unzip:
```
>> unzip test.zip
Archive:  test.zip
  inflating: .gitignore
  inflating: LICENSE
>> ls -alh . 
-rw-r--r--  1 ikrivosheev ikrivosheev  180 Jan  1  1980 .gitignore
-rw-r--r--  1 ikrivosheev ikrivosheev 1.1K Jan  1  1980 LICENSE
``` 

Work with zip tool:
```
>> zip test.zip .gitignore LICENSE
adding: LICENSE (deflated 41%)
adding: .gitignore (deflated 33%)
>> mv test.zip /tmp/test/
>> cd /tmp/test
>> unzip test.zip
>> ls -alh
-rw-r--r--  1 ikrivosheev ikrivosheev  180 Nov 10  2020 .gitignore
-rw-r--r--  1 ikrivosheev ikrivosheev 1.1K Nov 10  2020 LICENSE
```
You can `zip` save `time of last modification` for file.

**Comment by ikrivosheev** [comment]
Archive making with `zip`: [zip.zip](https://github.com/ouch-org/ouch/files/7965821/zip.zip)
Archive making with `ouch`: [ouch.zip](https://github.com/ouch-org/ouch/files/7965824/ouch.zip)
