### ISSUE TITLE
Add flag `-q/--quiet`

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#294]
`-q` flag description: "Silent all non-error messages."

EDIT: maybe `-q/--quiet` should make output less verbose, but keep the most useful stuff.

**Comment by a-moreira** [comment]
hey @marcospb19 , the idea here would be to use the `clap_verbosity_flag` [crate](https://docs.rs/clap-verbosity-flag/latest/clap_verbosity_flag/index.html), or to modify the macros etc?

**Comment by marcospb19** [comment]
@a-moreira we don't need `clap_verbosity_flag` here because by adding `--quiet` we'll have just two levels of verbosity, and that can be represented with just a boolean.

I was thinking about your suggestion, because we could add a `-v/--verbose` flag and use this crate, but I don't think it would be a good idea, every time I look up a `tar` usage example, people add the `-v` to make the output verbose and show all files that are being decompressed, so I think it's a good default as it is (at the time of writing, Ouch does this by default).

**Comment by marcospb19** [comment]
I created this issue in tens of seconds and didn't give it much thought, now that I think about it, it's better to have `-q/--quiet` suppress only the verbose output, like the list of files that are packed and unpacked from and into archives, but we should keep outputting the rest.

Without `--quiet`:
```
$ ouch c src archive.tar.gz
[INFO] Compressing 'src'.
[INFO] Compressing 'src/archive'.
[INFO] Compressing 'src/archive/mod.rs'.
[INFO] Compressing 'src/archive/tar.rs'.
[INFO] Compressing 'src/archive/zip.rs'.
[INFO] Compressing 'src/utils'.
[INFO] Compressing 'src/utils/colors.rs'.
[INFO] Compressing 'src/utils/file_visibility.rs'.
[INFO] Compressing 'src/utils/formatting.rs'.
[INFO] Compressing 'src/utils/mod.rs'.
[INFO] Compressing 'src/utils/fs.rs'.
[INFO] Compressing 'src/utils/question.rs'.
[INFO] Compressing 'src/commands'.
[INFO] Compressing 'src/commands/list.rs'.
[INFO] Compressing 'src/commands/compress.rs'.
[INFO] Compressing 'src/commands/decompress.rs'.
[INFO] Compressing 'src/commands/mod.rs'.
[INFO] Compressing 'src/accessible.rs'.
[INFO] Compressing 'src/error.rs'.
[INFO] Compressing 'src/list.rs'.
[INFO] Compressing 'src/macros.rs'.
[INFO] Compressing 'src/extension.rs'.
[INFO] Compressing 'src/cli.rs'.
[INFO] Compressing 'src/main.rs'.
[INFO] Compressing 'src/opts.rs'.
[INFO] Successfully compressed 'archive.tar.gz'.
```

With `--quiet`:
```
$ ouch c src archive.tar.gz --quiet
[INFO] Successfully compressed 'archive.tar.gz'.
```

**Comment by marcospb19** [comment]
Same applies to decompression, so I think it should just skip the files list.

**Comment by a-moreira** [comment]
@marcospb19 I agree :-)
I will do it. Do you think it makes sense to add a boolean input to the `info!(...)` macro so it simply ignores skips printing if the cli arg is true?

**Comment by marcospb19** [comment]
That macro already got a lot of arguments, so maybe it's better to call it inside of an if.

Also, we'll be using that `info!()` macro for outputting all the rest, so passing the same boolean value wouldn't work (you could use a hardcoded `true` but that sounds weird).

**Comment by a-moreira** [comment]
@marcospb19 ok, I created a PR [here](https://github.com/ouch-org/ouch/pull/325). I wasn't sure if I should send the `args.quiet` from the main function down the project, like we do with the other important cli args or not. Let me know what you think pls
