### ISSUE TITLE
Allow Ouch to decompress an archive into an existing folder

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#296]
Running

```
ouch decompress archive.tar --dir out
```

Asks the user if they want to delete the previous contents of `out` and overwrite them with the new contents from the archive.

Maybe it should add the new contents to the already existing folder, asking for overwrites every time some file conflicts (this is already the behavior when not using the `-d/--dir` flag)

**Comment by a-moreira** [comment]
hey @marcospb19, I'd like to do this as a starter  :-)
I've created a PR to do this, but it's rather straightforward I guess. Let me know if something is wrong or if you want any other stuff to be implemented: https://github.com/ouch-org/ouch/pull/321
