### ISSUE TITLE
Can't use lz4 formate

### ISSUE THREAD

**Issue by mlch911** [ouch-org/ouch#305]
### Version

0.3.1

### Description

ouch can't use lz4 format.
I'm using a m1 mac. Installed ouch and lz4 through homebrew.
How can I fix this ?

### Current Behavior

```shell
$ ouch c /Applications/Xcode14.1.0.app Xcode14.1.0.app.tlz4
[ERROR] Cannot compress to 'Xcode14.1.0.app.tlz4'.
 - You shall supply the compression format

hint: Try adding supported extensions (see --help):
hint:   ouch compress <FILES>... Xcode14.1.0.app.tlz4.tar.gz
hint:   ouch compress <FILES>... Xcode14.1.0.app.tlz4.zip
```

**Comment by figsoda** [comment]
lz4 is added in 0.4.0 (unreleased), once 0.4.0 is released, you should be able to use it without installing lz4

if you want to try it out, you can compile it from source on main or download an artifact from the most recent[actions](https://github.com/ouch-org/ouch/actions)

**Comment by figsoda** [comment]
0.4.0 is out now, this should be available once the package maintainers update the package

**Comment by marcospb19** [comment]
@mlch911 I checked https://repology.org/project/ouch/versions and the Homebrew version is up to date :+1:.
