### ISSUE TITLE
ouch 0.4.0 correctly erases parent dir when using `--dir .`

### ISSUE THREAD

**Issue by vrmiguel** [ouch-org/ouch#336]
### Version

0.4.0

### Description

`ouch d <archive> --dir .` asks to overwrite `.` and, if the response is yes, completely deletes the contents of `.`

### Additional Information

This behavior has already been fixed in HEAD, likely by #330 (or #321 ?). We just need to release `ouch 0.4.1` with this fix and the other smaller performance-related PRs as soon as possible

**Comment by vrmiguel** [comment]
@figsoda @marcospb19 

To reproduce

```
~ % cargo install ouch
~ % cd ouch 
ouch % ouch c src src.zip   
[INFO] Compressing 'src'.
[INFO] Compressing 'src/archive'.
[INFO] Compressing 'src/archive/tar.rs'.
[INFO] Compressing 'src/archive/mod.rs'.
[INFO] Compressing 'src/archive/zip.rs'.
[INFO] Compressing 'src/error.rs'.
[INFO] Compressing 'src/list.rs'.
[INFO] Compressing 'src/utils'.
[INFO] Compressing 'src/utils/question.rs'.
[INFO] Compressing 'src/utils/formatting.rs'.
[INFO] Compressing 'src/utils/mod.rs'.
[INFO] Compressing 'src/utils/colors.rs'.
[INFO] Compressing 'src/utils/file_visibility.rs'.
[INFO] Compressing 'src/utils/fs.rs'.
[INFO] Compressing 'src/accessible.rs'.
[INFO] Compressing 'src/main.rs'.
[INFO] Compressing 'src/commands'.
[INFO] Compressing 'src/commands/list.rs'.
[INFO] Compressing 'src/commands/decompress.rs'.
[INFO] Compressing 'src/commands/mod.rs'.
[INFO] Compressing 'src/commands/compress.rs'.
[INFO] Compressing 'src/opts.rs'.
[INFO] Compressing 'src/macros.rs'.
[INFO] Compressing 'src/extension.rs'.
[INFO] Compressing 'src/cli.rs'.
[INFO] Successfully compressed 'src.zip'.
ouch % ouch d src.zip --dir .
Do you want to overwrite '.'? [Y/n] y
[ERROR] failed to remove directory `.`
ouch % ls
ouch %
```

**Comment by figsoda** [comment]
it was probably fixed by https://github.com/ouch-org/ouch/pull/321.
we should be good for a new release, might also want to add the performance inprovements to the changelog

btw in case you didn't see https://github.com/ouch-org/ouch/pull/309, we can now make releases just by creating a tag, github actions will automatically build and upload the artifacts to a draft release, and all we need to do is to write the release notes and publish it

**Comment by vrmiguel** [comment]
Closing this since 0.4.1 has been published on GitHub and crates.io
