### ISSUE TITLE
Ouch delete img and iso extension if image is archive and you try to upack it

### ISSUE THREAD

**Issue by roland-rollo** [ouch-org/ouch#351]
### Version

ouch 0.4.1

### Description

Openwrt and few other projects compress their images (iso or img) to something like `xxx.iso.zip` or `yyy.img.gz`.
If I try decompress them, `ouch` will delete all extensions, so it will be file named `xxx` and not `xxx.iso` or `yyy` and not `yyy.img`.

Is there workaround for it? I tried to prevent it with
```
ouch decompress yyy.img.gz yyy.img
```
but it throw error
```
[ERROR] failed to canonicalize path `yyy.img`
 - File not found
```

**Comment by marcospb19** [comment]
@roland-rollo thanks for another report, could you check if #355 solves it as expected?
