### ISSUE TITLE
Alternative alias for listing: `ls`

### ISSUE THREAD

**Issue by orhun** [ouch-org/ouch#359]
Hello!

Intuitively, I tend to type `ouch ls` rather than `ouch l` due to my heavy usage of `ls` in many other places. I think having a 1-letter alias is cool but hey, why not support `ls` which is more common for "listing operations".

It's not a life or death situation though, just wanted to share this suggestion. If you find this applicable, I would be more than happy to contribute. LMK!

Thanks 🐻

**Comment by marcospb19** [comment]
We can support multiple aliases with `clap`, this is easy to implement and seems like a cool addition.

I think having both is better than removing the previous one, WDYT? @orhun @figsoda

**Comment by figsoda** [comment]
sounds good to me, this is what I was thinking as well

**Comment by marcospb19** [comment]
@orhun PR is welcome!

You might want to use `visible_aliases` and pass both if you want them both on the `--help` message, and on completions (I think), if you think `ls` should be a hidden alias, you can use `alias` instead, don't forget to add a `CHANGELOG.md` entry in a improvements section :+1:.

**Comment by orhun** [comment]
> We can support multiple aliases with `clap`, this is easy to implement and seems like a cool addition.

> sounds good to me, that's what I was thinking as well

Great!

> I think having both is better than removing the previous one, WDYT? @orhun @figsoda

Yeah, I agree with this.

> @orhun PR is welcome!
> 
> You might want to use `visible_aliases` and pass both if you want them both on the `--help` message, and on completions (I think), if you think `ls` should be a hidden alias, you can use `alias` instead, don't forget to add a `CHANGELOG.md` entry in a improvements section +1.

Thanks! I will submit a PR soon.
