### ISSUE TITLE
It appears that the list function applied to a .zip is not returning all file names

### ISSUE THREAD

**Issue by luccahuguet** [ouch-org/ouch#363]
### Version

0.4.1

### Description

Soon after compressing a folder containing 936 files, and applying `ouch list filename.zip | length`, it does not return the expected result, and instead returns different values between 70 to 90% of the correct value. See bellow:

![image](https://user-images.githubusercontent.com/27565287/218170095-97034c10-5ff8-4131-8747-400c3ee35024.png)

### Current Behavior

Soon after compressing a folder containing 936 files, and applying `ouch list filename.zip | length`, it does not return the expected result and instead returns different values between 70 to 90% of the correct value.

### Expected Behavior

Soon after compressing a folder containing 936 files, and applying `ouch list filename.zip | length`, it should return 936.

### Additional Information

OS: Fedora 37
Term. Emulator: Alacritty
Term. Multiplexer: Zellij
Shell: nushell

**Comment by marcospb19** [comment]
Just to be sure, you're running `ouch l` for the same archive and getting different results right? This file is not being mutated.

**Comment by figsoda** [comment]
I was able to reproduce the behavior you mentioned, but you might be misunderstanding what `length` does in nushell

```console
$ length --help                                                                                                                                   02/10/2023 07:39:56 PM
Count the number of elements in the input.

Usage:
  > length {flags}

Flags:
  -h, --help - Display the help message for this command
  -c, --column - Show the number of columns in a table

Signatures:
  list<any> | length -> <int>
  <table> | length -> <int>

Examples:
  Count the number of items in a list
  > [1 2 3 4 5] | length

  Count the number of columns in a table
  > [{columnA: A0 columnB: B0}] | length -c
```

`length` does not count the number of lines in the command output, instead it outputs the length of nushell list or table.

```console
$ ^seq 1 42 | length
1
```

What you are looking for is `wc -l`, so that would be `ouch list filename.zip | wc -l`. This command works as expected for me and outputs the same number on every run.

**Comment by marcospb19** [comment]
@luccahuguet can you test with `wc -l` (or `--lines`)?

**Comment by figsoda** [comment]
`ouch list filename.zip | lines | length` seems to also work, this is probably the way to go if you want to go full nushell builtins

**Comment by luccahuguet** [comment]
Thank you for the fast response @marcospb19 and @figsoda, indeed I misunderstood the way ouch outputs the result, which is a single string.

I can attest that both `wc -l` and the ` | lines  | length` approach work well!

Excuse me for the false alarm, at least I learned. 

So tools outside of the nushell world will probably work differently from nushell and its "everything is a table" philosophy...

Also: Ouch is a great project! Grateful to be using it.
