### ISSUE TITLE
Suggests to use --format which doesn't exist

### ISSUE THREAD

**Issue by freijon** [ouch-org/ouch#397]
### Version

0.4.1

### Description

I tried using a format which doesn't exist which results in this message:

> [ERROR] Cannot compress to 'metadata.xml.blubb'.
> - You shall supply the compression format
>
>hint: Try adding supported extensions (see --help):
> hint:   ouch compress <FILES>... metadata.xml.blubb.tar.gz
> hint:   ouch compress <FILES>... metadata.xml.blubb.zip
> hint:
> hint: Alternatively, you can overwrite this option by using the '--format' flag:
> hint:   ouch compress <FILES>... metadata.xml.blubb --format tar.gz

The hint suggests I can use `--format` to force a format.

But when I try the proposed command I get an error:

❯ ouch compress metadata.xml metadata.xml.blubb --format tar.gz

> error: Found argument '--format' which wasn't expected, or isn't valid in this context
> 
>   If you tried to supply '--format' as a value rather than a flag, use '-- --format'
> 
> Usage: ouch compress <FILES|OUTPUT>
> 
> For more information try '--help'

### Current Behavior

Gives an error that `--format` doesn't exist

### Expected Behavior

It should either:
- not show the misleading hint
- actually do what is written in the hint and force the provided format

**Comment by figsoda** [comment]
> actually do what is written in the hint and force the provided format

`--format` was introduced in #341 but not yet in a release

**Comment by marcospb19** [comment]
update 4 months later: I didn't make a release, @figsoda by chance, do you have the bandwidth to do so?

**Comment by figsoda** [comment]
version bump PR: #477

**Comment by marcospb19** [comment]
[0.4.2 got released!](https://github.com/ouch-org/ouch/releases/tag/0.4.2)
