### ISSUE TITLE
Crash when files in ZIP have no date

### ISSUE THREAD

**Issue by freijon** [ouch-org/ouch#411]
### Version

0.4.1

### Description

When trying to decompress a ZIP that contains files with no modifying and/or creation date, `ouch` crashes.

### Current Behavior

`ouch` crashes with the following message

> [INFO] Created temporary directory /mnt/c/Users/jonas.frei/Documents/tmp/dl/./.tmpPENU32 to hold decompressed elements.
> [INFO] ".tmpPENU32/ch6f_34080_091a_1.dxf" extracted. (313.98KiB)
> thread 'main' panicked at 'Zip archive contains a file with broken 'last modified time': ComponentRange { name: "month", minimum: 1, maximum: 12, value: 0, conditional_range: false }', src/archive/zip.rs:267:10
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### Expected Behavior

Shouldn't crash, use current datetime

### Additional Information

I think usually the files in a ZIP do have this metadata. Those ZIP files were generated by a tool that apparently doesn't include this information.

**Comment by freijon** [comment]
Here you go: [411-example.zip](https://github.com/ouch-org/ouch/files/11427801/411-example.zip)

**Comment by marcospb19** [comment]
Thank you! Opening a PR.
