### ISSUE TITLE
Help message is incomplete and wrong

### ISSUE THREAD

**Issue by freijon** [ouch-org/ouch#426]
### Version

0.4.1

### Description

When running `ouch --help` I see a message which doesn't list `ouch list` but shows its help-text

### Current Behavior

Running `ouch --help` shows:

```
A command-line utility for easily compressing and decompressing files and directories.

Supported formats: tar, zip, bz/bz2, gz, lz4, xz/lz/lzma, zst.

Repository: https://github.com/ouch-org/ouch

Usage: ouch [OPTIONS] <COMMAND>

Commands:
  compress
          Compress one or more files into one output file [aliases: c]
  decompress
          List contents of an archive [aliases: l]
  help
          Print this message or the help of the given subcommand(s)

Options:
  -y, --yes
          Skip [Y/n] questions positively

  -n, --no
          Skip [Y/n] questions negatively

  -A, --accessible
          Activate accessibility mode, reducing visual noise

          [env: ACCESSIBLE=]

  -H, --hidden
          Ignores hidden files

  -q, --quiet
          Silences output

  -g, --gitignore
          Ignores files matched by git's ignore files

  -h, --help
          Print help information (use `-h` for a summary)

  -V, --version
          Print version information
```

...indicating that `ouch decompress` "List contents of an archive [aliases: l]". The explanation of `ouch decompress` is missing completely

The sub-command `list` is not showed in the help, but running `ouch list --help` works fine.

### Expected Behavior

Help text should be complete and correct

**Comment by figsoda** [comment]
I can't reproduce this. Does this happen every time you run `ouch --help`?

**Comment by freijon** [comment]
I'm sure I'm using 0.4.1 - It's a self-compiled binary (Gentoo package) which uses the 0.4.1 release archive.
I did some investigation and was able to narrow it down... It only happens:

- On my virtual machines (SSH)
- When using [zellij](https://zellij.dev/). If I quit `zellij` and run `ouch --help` directly without multiplexing, the help is displayed correctly
- On my PC (no SSH) it also works fine while using `zellij`

summary: It's 100% reproducible on my VMs over SSH with `zellij`. Otherwise I can't reproduce the issue.

**Comment by figsoda** [comment]
I can't reproduce this in zellij either. What terminal emulator are you using? and can you try redirecting it to a file (`ouch --help > foo`) and see if it still happens?

**Comment by freijon** [comment]
`ouch --help > foo` yields a correct help text. This leads me to believe that it's actually a `zellij` over ssh issue and everything is fine with `ouch`. In the mean time I was also in contact with the `zellij` devs and they believe it could indeed be a bug on their side - but it will be hard to reproduce. Anyway, it's most likely not an `ouch` issue, so I'll close this issue.
