### ISSUE TITLE
Add support for zstd

### ISSUE THREAD

**Issue by djc** [ouch-org/ouch#44]
Would be nice to have. Especially if it defaulted to multithreaded operation (unlike upstream).

**Comment by marcospb19** [comment]
Seems to be viable, docs.rs/zstd has the decoders that we need, however, they don't support multiple threads.

**Comment by marcospb19** [comment]
Status update: I implemented it but got a linker error, could not solve it and got busy with other stuff.

I'm optimistic that it is a solvable error, however, I haven't figured it out yet, and if it requires a new library to be installed, we would need to stick to the `musl` toolchain, this could force us to drop support for some platforms.
