### ISSUE TITLE
If the compressed file name contains a dot, ouch use it as a folder name until then.

### ISSUE THREAD

**Issue by jeiea** [ouch-org/ouch#467]
### Version

0.4.1

### Description

It seems default extraction directory follows archive file name, but before dot.

It is weird with the archive like `1. what the.zip`.

```
➜  tmp touch a b
➜  tmp ouch c a b 1.a.zip
[INFO] Compressing 'a'.
[INFO] Compressing 'b'.
[INFO] Successfully compressed '1.a.zip'.
➜  tmp ouch d 1.a.zip
[INFO] Created temporary directory /Users/jeiea/tmp/./.tmpsIwRIS to hold decompressed elements.
[INFO] ".tmpsIwRIS/a" extracted. (0B)
[INFO] ".tmpsIwRIS/b" extracted. (0B)
[INFO] Successfully moved /Users/jeiea/tmp/./.tmpsIwRIS to ./1.
[INFO] Successfully decompressed archive in current directory (2 files).
➜  tmp ls
1       1.a.zip a       b
```

### Current Behavior

`ouch d 1.a.zip` extracts contents to directory `1`.

### Expected Behavior

`ouch d 1.a.zip` should extract contents to directory `1.a`.

**Comment by figsoda** [comment]
Could you test if this is still reproducible on the main branch? #355 should be able to fix this

**Comment by jeiea** [comment]
Yes it seems to be resolved. Although ouch says it cannot find extension.

**Comment by marcospb19** [comment]
> Yes it seems to be resolved. Although ouch says it cannot find extension.

@jeiea if that's reproducible can you open a dedicated issue?
