### ISSUE TITLE
Panic with large archive file

### ISSUE THREAD

**Issue by jeiea** [ouch-org/ouch#468]
### Version

0.4.1

### Description

When list large archive file and piping it to less(`ouch l archive.zip | less`) and press q, the following panic occurs.

I can't provide problematic archives but they were generally large (>4GB)

```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1009:9
stack backtrace:
   0:        0x107053537 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfa956040e2b11918
   1:        0x106f8d8aa - core::fmt::write::h067a4008cd9b8dc3
   2:        0x107040f2c - std::io::Write::write_fmt::h81ba594bfcc9a2cf
   3:        0x107053326 - std::sys_common::backtrace::print::h3823fea5c914c1de
   4:        0x1070467e6 - std::panicking::default_hook::{{closure}}::h3de0b4d5438777ae
   5:        0x1070464e0 - std::panicking::default_hook::h4e302d7e271a7df1
   6:        0x1070472c5 - std::panicking::rust_panic_with_hook::hfed4339f2d9efad3
   7:        0x107053994 - std::panicking::begin_panic_handler::{{closure}}::hbf6670c08406204e
   8:        0x1070538f8 - std::sys_common::backtrace::__rust_end_short_backtrace::h0cc5cadabed9b818
   9:        0x107046be2 - _rust_begin_unwind
  10:        0x1070f1603 - core::panicking::panic_fmt::h9d35b916792336ed
  11:        0x10702c64e - std::io::stdio::_print::h7d08be473e8d6aa0
  12:        0x106f227b8 - ouch::list::print_entry::h0df929d57fae5dd1
  13:        0x106f14fd6 - ouch::commands::list::list_archive_contents::h3220a10c1d2d1544
  14:        0x106f19c40 - ouch::commands::run::h61a8fe3795b659cd
  15:        0x106f2a298 - ouch::main::he4d76406b30a4a5d
  16:        0x106ed5126 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfd35b80db7aebdd0
  17:        0x106f360ce - _main
  18:     0x7ff8024fe41f - <unknown>
```

### Current Behavior

Panic.

### Expected Behavior

No panic should occurs.

**Comment by figsoda** [comment]
Could you test if this is fixed on main? https://github.com/ouch-org/ouch/pull/354 should be able to fix this

**Comment by jeiea** [comment]
No, it is not resolved. I'm confused because it seems like you fixed the file compression part when the problem is the file decompression.

**Comment by figsoda** [comment]
I can't reproduce the error with a zip file with a single file created from `/dev/random`, so I'm not exactly sure what happened here. From the error message, it looks like maybe `less` quit before `ouch` was able to finish decompressing? Can you consistently reproduce the error if you wait for the output to complete before pressing `q`?

**Comment by jeiea** [comment]
Yes, I can consistently reproduce this error. And no the error does not occur if I see the end of output by pressing `Gq`.

Sorry I can't provide example because original file is for company. But I think it may be tested with an archive with many files.

**Comment by figsoda** [comment]
> No, it is not resolved.

Have you tested it on main, or was it just based on the fact that the PR was irrelevant?

I am asking because https://github.com/ouch-org/ouch/pull/339 might have fixed this, since the switch from `println!` to `let _ = writeln!` should be able to quietly absorb the errors.

**Comment by jeiea** [comment]
Ah, it looks like I didn't tested against main branch. It think it is resolved.
