### ISSUE TITLE
Be compatible with tee utility

### ISSUE THREAD

**Issue by jeiea** [ouch-org/ouch#472]
## Steps to reproduce
Environment: macOS Ventura 13.4.1(c)
ouch: main branch (1d540f5cd4a58adc4609d96c9f5b4c46a4ba68af)

`ouch d anyfile.zip | tee log.txt`

## Expected behavior

log.txt should contain any outputs.

## Actual behavior

log.txt is zero bytes.

**Comment by figsoda** [comment]
try doing `ouch d anyfile.zip 2>&1 | tee log.txt` instead

**Comment by jeiea** [comment]
I don't know but believe there is the reason that it uses stderr instead of stdout.

**Comment by marcospb19** [comment]
> I don't know but believe there is the reason that it uses stderr instead of stdout.

@jeiea we'd like to add a `stdout` flag in the future future to output the compression/decompression results, so we decided that keeping logs in `stderr` at all times would be better.
