### ISSUE TITLE
Check the compression format of input files through MIME types 

### ISSUE THREAD

**Issue by vrmiguel** [ouch-org/ouch#5]
`ouch` currently determines the compression format of its input files through their extensions, which isn't ideal

**Comment by marcospb19** [comment]
Our usage is now totally guided by the extensions, we cannot fully rely on MIME types, but maybe add some checks before extracting some file.

Like, if we are extracting a .tar.gz file, but it looks like something else, ask via dialog.rs/Confirmation if the user wants to proceed.

But idk, this isn't an impactful change.

**Comment by mulimoen** [comment]
I encountered a `.tgz` file which I had to rename to `.tar.gz` to exctract. It would be great if this "just worked" by testing for e.g. file signatures.

**Comment by marcospb19** [comment]
@mulimoen what if we support `.tgz`?

**Comment by mulimoen** [comment]
@marcospb19 That would work just as well for me!

**Comment by marcospb19** [comment]
Closing after some internal discussions, we think it's better to check the MIME file types just to give the users previous advice when trying to decompress something that does not match up.
