### ISSUE TITLE
Having multiple archive tests running at once results in crazy crashes

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#50]
This issue **DOES NOT** affect any release of `ouch`, just running the development tests, however, it can turn out to be a pain for us developers in the future.

Spoiler: I HAVE NO CLUE OF WHAT IS GOING ON, and I've been trying to understand this issue for some time.

# How to make it break

At the time of writing, this is (almost) the tests of archive compressing and decompressing ([click here to jump to the code](https://github.com/ouch-org/ouch/blob/1a67da03ed4b747e89619b0060082046019a35cf/tests/compress_and_decompress.rs#L10-L31)):
```rust
#[test]
/// Tests each format that supports multiple files with random input.
fn test_each_format() {
    test_compressing_and_decompressing_archive("tar");
    test_compressing_and_decompressing_archive("tar.gz");
    test_compressing_and_decompressing_archive("tar.bz");
    test_compressing_and_decompressing_archive("tar.bz2");
    test_compressing_and_decompressing_archive("tar.xz");
    test_compressing_and_decompressing_archive("tar.lz");
    test_compressing_and_decompressing_archive("tar.lzma");
    test_compressing_and_decompressing_archive("zip");
    test_compressing_and_decompressing_archive("zip.gz");
    test_compressing_and_decompressing_archive("zip.bz");
    test_compressing_and_decompressing_archive("zip.bz2");
    test_compressing_and_decompressing_archive("zip.xz");
    test_compressing_and_decompressing_archive("zip.lz");
    test_compressing_and_decompressing_archive("zip.lzma");
}
```

It works, but let's say I try to split some of these into different test functions.

```rust
#[test]
fn test_zip() {
    test_compressing_and_decompressing_archive("zip");
    test_compressing_and_decompressing_archive("zip.gz");
    test_compressing_and_decompressing_archive("zip.bz");
    test_compressing_and_decompressing_archive("zip.bz2");
    test_compressing_and_decompressing_archive("zip.xz");
    test_compressing_and_decompressing_archive("zip.lz");
    test_compressing_and_decompressing_archive("zip.lzma");
}

#[test]
fn test_tar() {
    test_compressing_and_decompressing_archive("tar");
    test_compressing_and_decompressing_archive("tar.gz");
    test_compressing_and_decompressing_archive("tar.bz");
    test_compressing_and_decompressing_archive("tar.bz2");
    test_compressing_and_decompressing_archive("tar.xz");
    test_compressing_and_decompressing_archive("tar.lz");
    test_compressing_and_decompressing_archive("tar.lzma");
}
```

Or even one test per `test_compressing_and_decompressing_archive` call.

## What breaks?

When we run more than one test at once, a lot of stuff break, here are some symptoms:
- A lot of "File or directory not found"
  - Files passed for compression disappear before opening (including opening for .zip archive building)
  - Decompressed files may be disappearing too
- Compared file contents after compressing and decompressing suddenly mismatch

## My suspections:

I suspect it is caused because different tests are run in different threads.

Ouch is _100% unsafe free_, and I can't find where we could be causing this problem, so I do suspect it has something to do with some library we are using, even thought it is very unlikely.

- Maybe `tempfile::TempDir` is messing up with drop in different threads?
- `rand::SmallRng` is very unlikely to have an non-documented bug like this.
- Any compression crate, like `flate2`, `bzip2`, `tar`, `xz2` or `zip`?

**Comment by dlight** [comment]
([The failing code](https://github.com/ouch-org/ouch/blob/multithreaded-testing/tests/compress_and_decompress.rs]))

Since [each test creates its own directory](https://github.com/ouch-org/ouch/blob/multithreaded-testing/tests/compress_and_decompress.rs#L87), they shouldn't be touching the same files.. but by the description of the bug, it seems they are.

I think the next step is to actually check which files each test writes and reads, and whether there is any overlap.

**Comment by marcospb19** [comment]
@vrmiguel @dlight @figsoda Ok, I figured it out.

Changing directories with `std::env::set_current_dir` in one test actually changes it for all other tests.

Ouch enters directories using `set_current_dir` in order to simplify the relative path handling, Zip/Tar functions assume that you're inside of a specific folder.

Files suddenly went missing, of course, the process just `cd`'d another directory.
