### ISSUE TITLE
Ouch explodes when parallel decompression requires `stdin` interaction

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#510]
### Version

0.4.2

### Description

Parallelism added in #337 doesn't account for the fact that `Ouch` asks questions when decompressing.

### Current Behavior

![image](https://github.com/ouch-org/ouch/assets/38900226/06e02b40-19a1-475f-b651-82cee461c861)

`Do you want to overwrite 'dir/ouch'? [Y/n] Do you want to overwrite 'dir/ouch'? [Y/n] Do you want to overwrite 'dir/ouch'? [Y/n] Do you want to overwrite 'dir/ouch'? [Y/n] Do you want to overwrite 'dir/ouch'? [Y/n] Do you want to overwrite 'dir/ouch'? [Y/n] Do you want to overwrite 'dir/ouch'? [Y/n] Do you want to overwrite 'dir/ouch'? [Y/n] ^C`

**Comment by marcospb19** [comment]
A few ways out of this: 

1. Regress decompression parallelism.
2. Create a complex system separating the `main` thread from decompression and compression threads so they communicate via messages, and the `main` thread handles the logic of outputting and reading input, so this never happens.

The latter is optimal, Ouch needs to separate the text outputting from the compression/decompression threads to achieve better performance and fix #77.

_However_, we don't have the workforce available to do such a system and maintain it in the long run, this project is stalled already with easy-to-fix bugs, imagine complex ones, let's not shoot our feet again.

@figsoda thoughts?

**Comment by figsoda** [comment]
> 2\. Create a complex system separating the `main` thread from decompression and compression threads so they communicate via messages, and the `main` thread handles the logic of outputting and reading input, so this never happens.

If we want a simpler solution, we can probably just have a static lock for Y/n prompts

**Comment by figsoda** [comment]
> But how to stop output from other threads from getting in the way of Y/n prompts?

Good point, I don't think that's possible without having more complex system then

> Do we stop all progress by holding a `stderr` lock?

I don't think it works just by holding the stderr lock. If you mean the static lock, I think that might have a performance implication if we have to check every time we print anything to stderr

**Comment by marcospb19** [comment]
This should be fixed when #643 is closed by the PR #642.

**Comment by marcospb19** [comment]
Fixed! #643 was solved by #642 :tada:
