### ISSUE TITLE
Add compression level configuration flags

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#52]
Planned flags:

## `--level LEVEL_NUMBER`
From 1 to 10, `ouch` should "translate" that range for each format, considering that some formats use higher numbers than others.

## `--fast`

Less intensive compressing, we can seek for the best defaults aiming for 50% of time taken (run in half the time).

## `--slow`

More intensive compressing, takes longer, we shall look for defaults that take up to double the time, but also, we'll need to establish a RAM limit.

Some compression methods have a memory usage table that explains how much a certain level can use.

**Comment by marcospb19** [comment]
Zip does not support this, and I'd prefer not to have this flag implemented only for some of the formats.

**Comment by marcospb19** [comment]
docs.rs/zip now supports [specifying compression level](https://docs.rs/zip/latest/zip/write/struct.FileOptions.html#method.compression_level)

This issue is unblocked.

**Comment by figsoda** [comment]
we should also allow specifying the compression method zip is using since the range of possible levels differs
