### ISSUE TITLE
Decompressing tar.gz panics

### ISSUE THREAD

**Issue by psibi** [ouch-org/ouch#53]
Steps to reproduce:

1. wget -O revealjs.tar.gz https://github.com/hakimel/reveal.js/archive/3.9.2.tar.gz
2. Try to uncompres it
```
❯ ouch ./revealjs.tar.gz
[INFO] "/home/sibi/github/transcripts/justl/revealjs.tar.gz" extracted into memory (4.25 MB).
[INFO] attempting to decompress "revealjs.tar"
[INFO] "./pax_global_header" extracted. (52.00 B)
thread 'main' panicked at 'No such file or directory (os error 2)', src/error.rs:96:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Version used:

```
❯ ouch --version
ouch 0.1.5
```

**Comment by psibi** [comment]
I could decompress it fine using `tar`:

```
tar xvf ./revealjs.tar.gz
```

**Comment by vrmiguel** [comment]
It appears we've fixed this somehow after the release of 0.1.5

```
❯ ouch reveal.js-3.9.2.tar.gz 
[INFO] "/home/vrmiguel/ouch/reveal.js-3.9.2.tar.gz" extracted into memory (4.25 MB).
[INFO] attempting to decompress "reveal.js-3.9.2.tar"
[INFO] "./pax_global_header" extracted. (52.00 B)
thread 'main' panicked at 'No such file or directory (os error 2)', /home/vrmiguel/.cargo/registry/src/github.com-1ecc6299db9ec823/ouch-0.1.5/src/error.rs:96:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

❯ target/release/ouch reveal.js-3.9.2.tar.gz 
[INFO] "./pax_global_header" extracted. (52.00 B)
[INFO] "./reveal.js-3.9.2/" extracted. (0 B)
      ...
[INFO] "./reveal.js-3.9.2/test/test.js" extracted. (22.84 kB)
[INFO]: Successfully uncompressed bundle at '.'.
```

**Comment by marcospb19** [comment]
We made a lot of commits since then, including the whole rework of our compress and decompress logic, so we can close it after a new release?

**Comment by vrmiguel** [comment]
@psibi We just released version 0.1.6!

Can you confirm if this new version solves the problem?

**Comment by marcospb19** [comment]
Note: version 0.1.6 does not have binaries in the github available, and our installation script is temporarly broken.

So @psibi how are you installing `ouch`? Do you get it from nixpkgs? 

About that, I see in https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/compression/ouch/default.nix#L8 that it's pointing to the old repository location, maybe it should be updated.

Extra question, this package that you created uses `cargo` to compile, or pre-built binary files to install? I have never used Nix.

**Comment by psibi** [comment]
@vrmiguel Thanks, that's great to hear!

Can you do a new git tag for the released version of `0.1.6` ?

@marcospb19 

> Do you get it from nixpkgs?

Kind of, but since `ouch` is not yet part of stable, I get it from my own nix derivations: https://github.com/psibi/dotfiles/tree/master/machines/packages/ouch (since I don't rely on `unstable`). But `ouch` should be a part of next stable release. :-)

> pointing to the old repository location, maybe it should be updated.

Yeah, it would be convenient if a new git `tag` is created for the release. Either I can update it or the nixpkgs bot will update after a couple of days IIRC. Or PR's welcome from you too. :-)

> this package that you created uses cargo to compile, or pre-built binary files to install?

We build it using cargo based on the nix derivation files.

**Comment by marcospb19** [comment]
@psibi sorry for the waiting, I made the 0.1.16 released in GitHub, with a new tag too.

**Comment by psibi** [comment]
Thank you!
