### ISSUE TITLE
Supporting unrar introduces licensing issues

### ISSUE THREAD

**Issue by cyqsimon** [ouch-org/ouch#565]
The underlying C++ library of unrar.rs uses [a proprietary license](https://github.com/muja/unrar.rs/blob/master/unrar_sys/vendor/unrar/license.txt) that includes some hostile restrictions. As explained by [Fedora Wiki](https://fedoraproject.org/wiki/Licensing:Unrar), these restrictions make it GPL-incompatible and non-free.

- The good news is that `ouch` does not distribute unrar sources directly, which means it's not subjected to the requirements of term 2, which means it can continue to be licensed under MIT license (I think; obligatory "not a lawyer").
- The bad news is that building `ouch` would still require non-free code, which makes it legally impossible to include it in FOSS-only distributions like Debian and Fedora, or to build it using third-party build services with FOSS-only TOS (namely Fedora COPR).

As I see it, there are two ways to solve this problem:
1. Feature-gate unrar support
2. Migrate to a free unrar library (e.g. [unrar-free](https://gitlab.com/bgermann/unrar-free), which is shipped by Fedora)

Of course, the two are not mutually exclusive. I will submit a PR for the feature-gate first.

**Comment by marcospb19** [comment]
yo I think we forgot to close this one!
solved by #566.

**Comment by cyqsimon** [comment]
Yeah, I suppose we can consider this completed.

The ideal solution would of course be to switch to a FOSS unrar library, but until such demand arises and someone volunteers to work on it, I think this is good enough for now.
