### ISSUE TITLE
The "Dependencies" section of the README seems outdated.

### ISSUE THREAD

**Issue by ilyagr** [ouch-org/ouch#568]
https://github.com/ouch-org/ouch/blob/0dbbd3b8825d1bb8f985b3e384cdd987d5f4d40f/README.md?plain=1#L166-L176

This mentions a download script that no longer seems to exist. Also, it's unclear what systems these dependencies are necessary on (what about each version of the official binaries?), or whether these are build-time or runtime dependencies.

**Comment by marcospb19** [comment]
Thanks for spotting this, yeah the script does not exist anymore.

Dependencies are runtime dependencies, but I'll follow up with a PR to clarify.
