### ISSUE TITLE
Support for encrypted archives

### ISSUE THREAD

**Issue by TLATER** [ouch-org/ouch#576]
Some archive types like 7z can be encrypted - looks like `sevenz-rust` [at least partially supports en-/decrypting such archives](https://crates.io/crates/sevenz-rust#decompress-a-encrypted-7z-file).

I don't personally have much of a use case for encrypting such archives, but this has really become a swiss army knife for decompressing various archives - it's annoying to need to install other packages when I stumble upon an encrypted one, so it would be really nice if at least decryption was supported.

**Comment by marcospb19** [comment]
related to #326
