### ISSUE TITLE
Create AUR package `ouch-bin`

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#58]
So aur helpers users can install it like:

```sh
yay -S ouch
# while also being possible:
# yay -S ouch-bin
```

Using the suffix `-bin` is a convention for when the installation just downloads a binary.

NOTE: passing `ouch` as an argument instead of the full name is achievable by using the `provides` field in the `PKGBUILD` file.

NOTE²: maybe in the future we will ship it with shell completions too.

**Comment by BachoSeven** [comment]
Once you get around to doing this, I suggest making a third package as well called `ouch-git` which pulls and builds from the latest commit. For an example, see `ripgrep-all`:

- https://aur.archlinux.org/packages/ripgrep-all/
- `-bin` https://aur.archlinux.org/packages/ripgrep-all-bin/
- `-git` https://aur.archlinux.org/packages/ripgrep-all-git/

**Comment by yigitsever** [comment]
I've published `ouch` and `ouch-git` packages on AUR,

- https://aur.archlinux.org/packages/ouch/
- https://aur.archlinux.org/packages/ouch-git/

`ouch-git` clones & builds the upstream (does not need manual updates on my part unless build process/url changes, users always get the latest commit) and as for `ouch`, I've subscribed this repository for releases :)

**Comment by marcospb19** [comment]
Thanks for you contribution @yigitsever!!!

That is essential for `ouch`, I dream of making it a useful tool like `rg, `bat`, `fd` and `git-delta`, and they all are in the official `pacman` mirrors, so I guess this is the first step!

Let me know if you are interested in packaging to `ouch-bin` too, our releases since 0.2.0 come with the binary come with binaries with name `"ouch-x86_64-linux-musl"`, I guess this would be the most useful way for people who don't want to download the Rust toolchain.

**Comment by marcospb19** [comment]
@yigitsever do you think it's better to have them in the repository, in each release, or both?

**Comment by yigitsever** [comment]
@marcospb19 definitely in the repository, `ouch` and `ouch-git` clone it anyway and `ouch-bin` can use the raw github url to download it.
Just double checked and `fd`, `ripgrep` and `bat` also ship their completion scripts in the repo :)

**Comment by marcospb19** [comment]
Thanks for the tips, and thanks for practically closing this issue!

I will be creating other issue to cover the completions and man pages shipping details :+1:.

Leaving this one open just to remember that we need to add README notes about the new AUR packages.

**Comment by marcospb19** [comment]
Update, we don't need to edit the README, this bad boi just detects it automatically:

![image](https://user-images.githubusercontent.com/38900226/140237491-53abcbda-fa22-4494-99c5-fb33e6a57b8e.png)

Ok awesome.

**Comment by murlakatamenka** [comment]
> @marcospb19 definitely in the repository, `ouch` and `ouch-git` clone it anyway and `ouch-bin` can use the raw github url to download it. Just double checked and `fd`, `ripgrep` and `bat` also ship their completion scripts in the repo :)

Sounds misleading. Completion files shouldn't be in the repo, they are build artifacts and should be included in release tarballs alongside binaries.

Check `fd`, `ripgrep` and `bat` CD workflows:

- https://github.com/BurntSushi/ripgrep/blob/ba535fb5a34f6d703fc652e8dfc23c0fed78fc74/.github/workflows/release.yml#L152-L162

- https://github.com/sharkdp/fd/blob/e8fe1508e25b17a923aced72275b96d4baaad602/.github/workflows/CICD.yml#L200-L204

- https://github.com/sharkdp/bat/blob/194e7bbcd1481efebfd154aaecdd1e696036476e/.github/workflows/CICD.yml#L307-L311

Only zsh completion files are maintained inside the repo (fd, ripgrep) but that's exceptions.

---

@marcospb19 from a packaging POV release tarball should have:
- binary
- completions
- man page (if exists)
- LICENSE

---

@yigitsever I can co-maintain `ouch` and `ouch-bin` packages if you wish, I maintain [a few other rusty packages](https://aur.archlinux.org/packages/?K=murlakatamenka&SeB=m).

**Comment by marcospb19** [comment]
I checked the other tools, I think it's a bit confusing, in https://github.com/sharkdp/bat/pull/1890 the contributor said:

> "Maybe in the future these can be autogenerated?"

However, the person who merged did not answered :thinking:.

`bat` seems to have them in the repository, but the CI @murlakatamenka showed do not use them, instead, they use what was generated at the `target` directory.

Anyways, thanks @murlakatamenka for the input, I ain't got the time **yet** to organize the releases so they're still a bit messy, but that will be improved for sure.

---

About having co-maintainers, I think that could be useful for `ouch`, when someone is not online or is just busy with some other stuff, so you could add `murlakatamenka` and `marcospb19` (me too, just in case).

But if @yigitsever does not think it's necessary and you can keep up no problems, than it's ok too, maybe you don't have problems with availability.

**Comment by marcospb19** [comment]
I was reading the `PKGBUILD` of the packages, I think `ouch-bin` is fine, but `ouch-git` and `ouch` can be broken because they are being built to the target `"$CARCH-unknown-linux-gnu"`.

But that adds runtime dependencies, `ouch` don't need dependencies specifically when built with `musl`.

**Comment by yigitsever** [comment]
> I was reading the `PKGBUILD` of the packages, I think `ouch-bin` is fine, but `ouch-git` and `ouch` can be broken because they are being built to the target `"$CARCH-unknown-linux-gnu"`.
> 
> But that adds runtime dependencies, `ouch` don't need dependencies specifically when built to target `"*-unknown-linux-musl"`.

@marcospb19 I've used https://wiki.archlinux.org/title/Rust_package_guidelines which links to https://doc.rust-lang.org/nightly/rustc/platform-support.html, 

Archlinux provides [namcap](https://wiki.archlinux.org/title/Namcap) utility which I use to check the resulting packages to catch silly mistakes. Currently it's only complaining that `zlib`, `bzip2` and `xz` are missing. Two of those packages are in the "base" Archlinux install, we can safely assume that they would be included in any machine that would like to install `ouch`. I'm not sure about `zlib`, that might have to be included explicitly so I asked in the #archlinux-aur irc channel to check (awaiting response),

`*-unknown-linux-musl` would bring `musl` as a dependency? There are also multiple ways to get `rustup` for Archlinux (https://wiki.archlinux.org/title/Rust#Installation) and I honestly don't know how that would play for different installations.

Other than that, I don't feel qualified in "static vs dynamic linking" debate so I've done some research regarding what other popular rust packages have done and `fd`, `paru`, `exa`, `rg` and `bat` use dynamic linking as far as I can tell from their `ldd` outputs,

All in all, `ouch` currently de facto has no runtime dependencies, relying on libc and the co. is a necessary evil (: zlib might have to be added but I honestly do not believe that would surprise anybody, or would cause an extra keypress during the installation, `git` relies on it! 

Regarding availability, at this moment I'm fine for time and don't think I'd need help for maintenance. If I fall behind or feel the need, I will contact @murlakatamenka through their mail address listed on aur,

> Sounds misleading. Completion files shouldn't be in the repo, they are build artifacts and should be included in release tarballs alongside binaries.

Regarding the completion scripts, I should clarify that I came across their completion scripts in their Github repositories. "Shipping in the repo" might've sounded misleading, sorry about that. Including completion scripts (and the license!) in tarballs would make my life much easier but that's upstream's decision :)

**Comment by marcospb19** [comment]
`bzip2` and `xz` are in `base`, so that's ok? I mean, `base` had some changes in the last year, can the AUR packages still rely on `base` and `base-devel` like before?

`zlib` is required by `libarchive` and `libarchive` is required by `pacman`. So I guess we can trust on `zlib` being always available (`linux`, `git`, `sudo` and `man-db` also require `zlib` directly or indirectly).

---

About the "static vs dynamic linking" part, in the benchmarks I ran the `musl` compiled version of `ouch` is faster, and I think it's also simpler to have everything in one static binary.

> *-unknown-linux-musl would bring musl as a dependency?

No, AFAIK the "targets" you set in rustup do not require any additional setup, and you could even compile to ARM Linux on x86 Windows, the compile is agnostic of what platform it's running on.

So I currently think that using `musl` would be a good idea, but if you run into any additional problems with it, we can discuss more and even reconsider.

---

> Including completion scripts (and the license!) in tarballs would make my life much easier

I'll be doing that soon! Short on time, but I'll have some for `ouch` soon.

**Comment by murlakatamenka** [comment]
Having `glibc`, `bzip2`, `xz` and `zlib` can't be an issue since it's in `base` package group. The easiest way to check it out is `pactree` from `paman-contrib`:

```sh
pactree base | rg '(glibc|zlib|xz|bzip2)'
```

That's Arch-specific though, can't speak for other distros.

---

`*-unknown-linux-musl` would bring `musl` as a dependency?

yes, it will be a make dependency

---

> Regarding availability, at this moment I'm fine for time and don't think I'd need help for maintenance. If I fall behind or feel the need, I will contact @murlakatamenka through their mail address listed on aur

okay @yigitsever 

---

@marcospb19 here is my take on benchmarking `glibc` vs `musl` versions of ouch.

1. Binaries compiled from source:

```sh
cargo build --release # x86_64-unknown-linux-gnu
cargo build --release --target=x86_64-unknown-linux-musl
```

2. Source is `pacman` package cache: 356 `tar.zst` files, 1.69 GiB in total.

3. `bench.sh`:

```sh
#!/bin/sh

SRC="/var/cache/pacman/pkg/*.tar.zst"
OUTDIR="/tmp/ouch_bench_dir"

hyperfine --warmup 1 \
    --prepare "rm -rf $OUTDIR" \
    "./target/release/ouch decompress $SRC -d $OUTDIR" \
    "./target/x86_64-unknown-linux-musl/release/ouch decompress $SRC -d $OUTDIR"
```

4. Results:

```sh
Benchmark 1: ./target/release/ouch decompress /var/cache/pacman/pkg/*.tar.zst -d /tmp/ouch_bench_dir
  Time (mean ± σ):     19.521 s ±  0.494 s    [User: 10.264 s, System: 9.045 s]
  Range (min … max):   19.203 s … 20.880 s    10 runs
 
Benchmark 2: ./target/x86_64-unknown-linux-musl/release/ouch decompress /var/cache/pacman/pkg/*.tar.zst -d /tmp/ouch_bench_dir
  Time (mean ± σ):     21.101 s ±  0.110 s    [User: 11.041 s, System: 9.843 s]
  Range (min … max):   20.941 s … 21.294 s    10 runs
 
Summary
  './target/release/ouch decompress /var/cache/pacman/pkg/*.tar.zst -d /tmp/ouch_bench_dir' ran
    1.08 ± 0.03 times faster than './target/x86_64-unknown-linux-musl/release/ouch decompress /var/cache/pacman/pkg/*.tar.zst -d /tmp/ouch_bench_dir'
```

So, in my case dynamically linked has definitely performed better than statically linked one.

I think there are use cases for both versions.

Dynamically linked one can be good for desktop.
Statically liked one is good as a portable swiss-army knife (`scp` to remote server, for instance).

**Comment by marcospb19** [comment]
> > *-unknown-linux-musl would bring musl as a dependency?
>
> yes, it will be a make dependency

Indeed, I edited my previous message where I confused on this.

---

> So, in my case dynamically linked has definitely performed better than statically linked one.

I assume that `musl` has an advantage with `.tar.gz` but loses with `.tar.zst`.

---

Now that I know that `*-gnu` and `*-musl` targets both require a library to build, I guess the best decision is to choose the gnu one, because it has tier 1 support, while musl is tier 2, and it's less likely that someone has `musl` installed in their machine, while `glibc` is guaranteed.

That is for `ouch` and `ouch-git` packages, does the same apply for `ouch-bin`? If so, I would need to add the gnu compiled binary to all releases.
