### ISSUE TITLE
Support "zst" and "zstd" for ZStandard

### ISSUE THREAD

**Issue by phip1611** [ouch-org/ouch#608]
The official extension for ZStandard-compressed files seems to be `.zstd`.
However, `ouch` uses `.zst`.

So I have to either use

`ouch compress  --format zst "$file" "$file.zstd"`
or
`ouch compress "$file" "$file.zst"` for auto detection

**Comment by phip1611** [comment]
Oh, I'm sorry. I was confused!

https://github.com/facebook/zstd says

> Zstandard, or zstd as short version

But later on the website they just use `.zst` - Sorry!
An alias might be helpful nevertheless

**Comment by marcospb19** [comment]
Hey @AntoniosBarotsis I'm now unsure if we should add this one.

Aliases make sense when two extensions are commonly accepted for a same file, like, `.yml` and `.yaml`.

But if `.zstd` shouldn't be a thing, then I think Ouch should give an error message so the user knows to correct it.

To help decide, @figsoda @vrmiguel any thoughts on this?

**Comment by AntoniosBarotsis** [comment]
I was confused because this issue stayed open even after the last reply by Phip but I guess it doesn't make too much sense on second thoughts. I thought I've seen the `.zstd` extension used elsewhere but it might be that I remember wrong or the person using it misused it 😅

**Comment by phip1611** [comment]
I apologize for confusing you with my confusion :)

**Comment by marcospb19** [comment]
no problem!!! I always do stuff like this
