### ISSUE TITLE
Improve [INFO] message when decompressing archives

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#67]
![image](https://user-images.githubusercontent.com/38900226/136265055-8d606361-3012-4666-9164-fc8c636e381c.png)

Suggestions:

- [x] Should change word "bundle" to "archive".
- [x] When the destination is `'.'`, output `current directory` instead.
- [x] Remove the `'./'` at the beginning of each file, they are pointless: `'./file'.` .
- [x] The command is called `decompress`, but here we have "uncompress", [seems to be a bit off](https://english.stackexchange.com/questions/56480/difference-between-uncompress-and-decompress/56483).

**Comment by marcospb19** [comment]
Changed the title, I was saying "uncompressing" again...

**Comment by exoego** [comment]
>  Should change word "bundle" to "archive".

This seems already resolved.
```
$ git grep bundle | wc -l
       0
```

**Comment by marcospb19** [comment]
Solved by #109 + #117 + #119.
