### ISSUE TITLE
Installation script broken, CI is not uploading artifacts for MacOS x86_64 job

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#68]
When checking the CI for specific commit (click on the :heavy_check_mark: and then details):
![image](https://user-images.githubusercontent.com/38900226/136285910-eceff14b-870c-412a-ae1c-eb3aa737390e.png)

The MacOS artifact is not there:
![image](https://user-images.githubusercontent.com/38900226/136286074-38999e58-6fae-44c0-a4a8-5cb5ee03f517.png)

Even if it succeeded.

**Comment by vrmiguel** [comment]
Closed by #69
