### ISSUE TITLE
Change .tmp file directory

### ISSUE THREAD

**Issue by valoq** [ouch-org/ouch#685]
When decompressing an archive, ouch will temporarily create a directory named .tmpXXXXXX (X = random char)
It may be better to use a path in XDG_DATA_HOME or a more specific path name to make sure no file conflicts occur.
A collision with a different application using the same path may be unlikely with 6 random characters, but this seems to be easy to avoid entirely.

**Comment by marcospb19** [comment]
I think calling it something like `.ouch-tmp-XXXXXX` could be enough for collisions, and more informative for users too.

Although, I don't know of any application that names things like we currently do.

**Comment by marcospb19** [comment]
Thanks for the suggestion! Will take a look for sure.
