### ISSUE TITLE
[Feature request] Extension support for bacpac/dacpac files

### ISSUE THREAD

**Issue by koalazub** [ouch-org/ouch#698]
Hey! I'd like to request support for bacpac/dacpac extensions. I'm currently unable to use ouch for de/compressing Microsoft's bacpac/dacpac files. 

This is my current workaround: 
```
zip -r new_database.bacpac *
```
instead of `ouch`

Definition of the file: 
> File format
A .dacpac is a compressed folder with a .dacpac extension, and similarly a .bacpac is a compressed folder with a .bacpac extension. An advanced user can unpack the file to view the multiple XML sections representing details of the origin, the objects in the database, and other characteristics. To unpack a .dacpac or .bacpac, replace the file extension with .zip and use a file compression utility to unzip the file.

Source: [Data Tier Applications](https://learn.microsoft.com/en-us/sql/relational-databases/data-tier-applications/data-tier-applications?view=sql-server-ver16#file-format)

**Comment by marcospb19** [comment]
Hi! Can you check if this command works for your usage case?

```
ouch decompress db.bacpac --format zip
```

**Comment by koalazub** [comment]
Oh this was for compressing the `bacpac` file as well. 

So decompressing appears to work, but the reason why I mentioned both decompressing and compressing is because I'm greeted with the error: 

> [ERROR] Cannot compress to 'dummy_folder.bacpac'.
 > - You shall supply the compression format


And even if I were to overwrite it with `--format` I still get: 

> ouch c dummy_folder.bacpac/ dummy_folder.bacpac --format bacpac
[ERROR] Invalid archive format
>  - Unsupported extension: bacpac

**Comment by marcospb19** [comment]
Yeah I see, but notice that the piece of text you put in the issue description suggests people to rename the file:

> To unpack a .dacpac or .bacpac, replace the file extension with .zip and use a file compression utility to unzip the file.

IMO, sadly, it's not worth it for us to add aliases to this extension, as even the Microsoft folks suggest you to just rename them as zip.
