### ISSUE TITLE
Decompress partially for files with multiple formats

### ISSUE THREAD

**Issue by marcospb19** [ouch-org/ouch#70]
# Problem

Currently, it's not possible to decompress a file partially.

Take `archive.tar.gz.xz` as an example, you might want to decompress it into:
- `archive.tar.gz`, without the `.xz` part, or
- `archive.tar`, without  the `.gz.xz` part.

# Current workaround

Decompress and compress it again.

```sh
ouch decompress archive.tar.gz.xz -o result
cd result
ouch compress * .* archive.tar 
```

Note that the shell expansion `.*` is necessary in case you have any hidden files.

# Suggested new solution

Adding a `--partial` (`-p`) flag that takes the extensions as a parameter.

```sh
# Only the .xz part
ouch decompress archive.tar.gz.xz --partial xz

# The file created:
ls archive.tar.gz
```

Another example:

```sh
# Correctly decompressing .xz.gz
ouch decompress file.txt.lzma.bz.xz.gz --partial xz.gz

# The file created:
ls file.txt.lzma.bz
```

First, check if the suffix is really present in the file passed as argument, if multiple files given, then **all** files should have the suffix, otherwise, give an usage error message.

**Comment by marcospb19** [comment]
<details>
  <summary>Implementation details ↓</summary>

Our decompression function is already flexible enough to do this, just would need to pass the correct arguments, containing the file extensions that need to be processed, and maybe the output file (not sure now).

https://github.com/ouch-org/ouch/blob/8bf087bbd7d5073ebebb921d5c963f0fd241123a/src/commands.rs#L153-L158
</details>

**Comment by figsoda** [comment]
should this be added to compress too? It wouldn't be very useful, just for the sake of the interface

**Comment by figsoda** [comment]
I was actually thinking of something like `ouch compress file archive.tar.gz -p` which would be equilvalent to `ouch compress file archive.gz && mv archive.gz archive.tar.gz`

Also just something I thought about, what if someone just wants to create a tarball with a tar file inside?

**Comment by marcospb19** [comment]
We cannot do this:
```sh
ouch compress file archive.tar.gz -p
```

Because there is no format in `file` to partially compress, right? So it would give an error message.

@figsoda maybe do you mean like:

```sh
ouch compress archive.tar archive.tar.gz -p
```

So you can manually _"activate"_ the partial compression?

**Comment by figsoda** [comment]
my bad, I forgot to finish the command, i meant to put `ouch compress file archive.tar.gz -p .tar` instead
Also edited the original comment

**Comment by marcospb19** [comment]
Oh, I got it, it's the same as that "1" I explained before, but you flipped what is specified.

Instead of -p .gz, -p .tar .

**Comment by marcospb19** [comment]
Closing after some discussion done in another issues, `--format` will replace partial compression and partial decompression.
